python lerobot/scripts/control_robot.py \
  --robot.type=sa100 \
  --control.type=record \
  --control.fps=30 \
  --control.single_task="pick up doll" \
  --control.tags='["sa100","tutorial"]' \
  --control.warmup_time_s=5 \
  --control.episode_time_s=30 \
  --control.reset_time_s=30 \
  --control.num_episodes=2 \
  --control.push_to_hub=false \
  --control.repo_id=my-notes/sa100_002 